FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -qq \
    && apt-get install -y -qq --no-install-recommends \
       bash bc binutils bzip2 build-essential ca-certificates cpio file \
       findutils git gzip libncurses-dev patch perl python3 python-is-python3 rsync sed \
       squashfs-tools tar unzip wget xz-utils \
    && rm -rf /var/lib/apt/lists/*
