#!/bin/sh
set -eu

cd /work/busybox-1.37.0
make allnoconfig >/tmp/exword-busybox-allnoconfig.log

cfg=/work/linux/scripts/config

enable_options() {
	for option in "$@"; do
		"$cfg" --file .config --enable "$option"
	done
}

"$cfg" --file .config --set-str CROSS_COMPILER_PREFIX "sh4-linux-gnu-"
"$cfg" --file .config --set-str EXTRA_CFLAGS "-mb -m4a-nofpu"
"$cfg" --file .config --set-str INIT_TERMINAL_TYPE "linux"
"$cfg" --file .config --set-str UNAME_OSNAME "GNU/Linux"
"$cfg" --file .config --set-val FEATURE_EDITING_MAX_LEN 256
"$cfg" --file .config --set-val FEATURE_EDITING_HISTORY 16

enable_options \
	STATIC LFS TIME64 INSTALL_APPLET_SYMLINKS FEATURE_BUFFERS_USE_MALLOC \
	FEATURE_PREFER_APPLETS FEATURE_SH_STANDALONE FEATURE_SH_NOFORK \
	FEATURE_EDITING FEATURE_TAB_COMPLETION \
	BUSYBOX INIT FEATURE_USE_INITTAB FEATURE_INIT_SCTTY \
	ASH ASH_OPTIMIZE_FOR_SIZE ASH_INTERNAL_GLOB ASH_JOB_CONTROL \
	ASH_ECHO ASH_PRINTF ASH_TEST SH_IS_ASH BASH_IS_NONE \
	FEATURE_HUMAN_READABLE FEATURE_UMOUNT_ALL \
	BASENAME CAT CHMOD CLEAR CP DATE DD DF DMESG ECHO ENV FALSE FREE \
	FEATURE_DF_FANCY \
	GREP HEAD HEXDUMP HOSTNAME ID KILL LN LS MKDIR MKNOD MOUNT MV \
	PRINTF PS PWD REBOOT HALT POWEROFF RM RMDIR SED SLEEP SYNC TAIL \
	TEST TEST1 TEST2 TOUCH TRUE UMOUNT UNAME UPTIME WC XXD \
	CMP CUT DIRNAME DU FEATURE_DU_DEFAULT_BLOCKSIZE_1K EXPR NICE NOHUP \
	READLINK FEATURE_READLINK_FOLLOW REALPATH SEQ SHA256SUM SORT \
	FEATURE_SORT_OPTIMIZE_MEMORY STAT TEE TR TRUNCATE UNIQ WHOAMI \
	FIND FEATURE_FIND_PRINT0 FEATURE_FIND_TYPE FEATURE_FIND_MAXDEPTH \
	XARGS FEATURE_XARGS_SUPPORT_QUOTES FEATURE_XARGS_SUPPORT_ZERO_TERM \
	MORE STRINGS TREE WHICH \
	FEATURE_FAST_TOP FUSER KILLALL LSOF PGREP PKILL PIDOF \
	FEATURE_PIDOF_SINGLE PMAP PSTREE BB_SYSCTL TOP \
	FEATURE_TOP_INTERACTIVE FEATURE_TOPMEM FEATURE_PS_WIDE FEATURE_PS_LONG PWDX \
	DEVMEM \
	LOSETUP FEATURE_MOUNT_LOOP FEATURE_MOUNT_LOOP_CREATE \
	BLKID FEATURE_BLKID_TYPE BLOCKDEV PARTPROBE \
	FEATURE_VOLUMEID_FAT FEATURE_VOLUMEID_EXFAT FEATURE_VOLUMEID_EXT \
	FEATURE_VOLUMEID_LINUXSWAP FEATURE_VOLUMEID_SQUASHFS \
	FDISK FEATURE_FDISK_WRITABLE FEATURE_GPT_LABEL \
	FEATURE_MOUNT_FLAGS FEATURE_MOUNT_FSTAB FEATURE_MOUNT_LABEL \
	MKSWAP MOUNTPOINT RESET RENICE SETSID STTY SWAPON SWAPOFF \
	FEATURE_SWAPON_PRI FEATURE_SWAPONOFF_LABEL TTY

# CPU percentage sampling and automatic top refresh both wait on timer
# events.  Keep those optional top features disabled until the EX-word TMU
# support is fixed; top itself remains useful with manual Space/Enter refresh.
# Keep ash arithmetic disabled as well: scripts in this image are deliberately
# arithmetic-free, which saves memory and avoids depending on timer-adjacent
# shell paths that have not yet been exercised on this appliance.

yes '' | make oldconfig >/tmp/exword-busybox-oldconfig.log
